### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by rahilwazir** [mre/fcat#12]
After installation, I'm getting the following error:

```bash
❯ rustc -V
rustc 1.30.0-nightly (73c78734b 2018-08-05)

❯ RUST_BACKTRACE=1 fcat ~/.zshrc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EINVAL)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: fcat::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by mre** [comment]
That's strange. A few ideas:

1. Does `cat ~/.zshrc` work as expected? (To check if the file exists and is readable)
2. Can you try `fcat /home/<yourusername>/.zshrc`? (To check if absolute paths work on your machine)
3. Can you try `cd && fcat .zshrc`? (To check if it works from the local dir)
4. We should get rid of the unwrap and add some proper error handling.

**Comment by rahilwazir** [comment]
@mre 

I tried your suggestion, here are the results

1. `cat ~/.zshrc` - WORKED!
2. `fcat /home/<yourusername>/.zshrc` - ERROR!
3. `cd && fcat .zshrc` - ERROR!

**Comment by mre** [comment]
Thanks. What's your Linux Kernel version?

**Comment by mre** [comment]
Oh, and does `fcat` work on other files or does it always fail?

**Comment by rahilwazir** [comment]
@mre 

> What's your Linux Kernel version?

```
4.17.3-200.fc28.x86_64
```

> does fcat work on other files or does it always fail?

Always fails no matter what the file extension/type is. `.html`, `.php`, `.js`, `.rs`, `.txt` and so on but nothing works.

**Comment by mre** [comment]
Very weird.
I guess it won't help to add error handling to narrow it down; we would simply get `EINVAL` again, just nicely formatted...

What's your filesystem?
Can you try on a different filesystem?
Can you try from within the provided Docker container (`make build sh` and then fcat a file)?

**Comment by rahilwazir** [comment]
> What's your filesystem?

ext4

> Can you try on a different filesystem?

Tried on `iso9660` (USB), `vfat` (boot), error persists

> Can you try from within the provided Docker container (make build sh and then fcat a file)?

It works within container :weary: but it only shows **Hello, world!** all the time. Even if I try to view the contents of any file, it just spits **Hello, world!**

![fcat-docker](https://user-images.githubusercontent.com/1818941/43836051-805244c2-9b2d-11e8-998c-37c19a085d30.gif)

**Comment by vbrandl** [comment]
Try updating the git repository and checkout the branch `fix/docker`.
I think the caching of the Rust compiler causes problems when building the image. The commits on this branch should fix the problem.

**Comment by rahilwazir** [comment]
@vbrandl Yup, it works now only in the container.

**Comment by mre** [comment]
Could you try mounting a folder into the container and `fcat`ing a file from it?

**Comment by vbrandl** [comment]
Now I'm just spitballing, but what version of `rustc` are you using? (Edit: nvm, just saw you posted the version already. Could you try using the stable compiler branch)
Also does this happen in both release and debug builds?
Can you maybe post an strace of your call to fcat? 
@mre could this have something to do with the buffersize and some OS-enforced limits?

**Comment by ArniDagur** [comment]
Attempting to debug this has nearly driven me crazy. I have, though, concluded a few things:

1. `fcat ~/.zshrc | cat` works, but `fcat ~/.zshrc` doesn't.
2. Running a similar program in C fails in the same way unless you pipe it to cat.
3. Splicing and tee-ing only between files and pipes seems to work fine in C.
4. It's the second splice call that fails, with the error is `EINVAL: Invalid argument`.
https://github.com/mre/fcat/blob/c938b62b462455c61c346e0e0efe012ad338a084/src/main.rs#L42-L49

I don't really know what I'm talking about, but `1` and `2` seem to suggest that `splice()` has problems outputting directly to stdout (as in what you see in the terminal)?

**Comment by mre** [comment]
Thanks for your feedback @ArniDagur.
For future reference, what's your OS, rustc, filesystem, and Linux kernel version?

**Comment by mre** [comment]
Some more things as suggested by @vbrandl:

* Does this happen in both release and debug builds?
* Can you maybe post an strace of your call to fcat?
* Can you try changing the buffersize to a smaller value (e.g. 1024) here https://github.com/mre/fcat/blob/master/src/main.rs#L19 and then recompile?

**Comment by vbrandl** [comment]
Could you paste a gist containing the equivalent C code, you used?

**Comment by ArniDagur** [comment]
Replying to @mre's first comment:

> For future reference, what's your OS, rustc, filesystem, and Linux kernel version?

Should I try doing `rustup update` and see if it changes anything? I kind of doubt it.

## Machine 1 (Modern desktop)
**OS:** `Arch Linux x86_64`
**Kernel:** `4.18.6-arch1-1-ARCH`
**Filesystem:** `ext4`
**rustc version:** `rustc 1.30.0-nightly (0f063aef6 2018-09-03)`
**gcc version (used to compile the C code):** `gcc (GCC) 8.2.1 20180831`

## Machine 2 (Dell XPS 13 9350 laptop)
I did a system upgrade (`pacman -Syu`) as of writing this; the issue still persists. I put the versions after the upgrade in brackets.

**OS:** `Arch Linux x86_64`
**Kernel:** `4.17.13-arch1-1-ARCH` [`4.18.6-arch1-1-ARCH`]
**Filesystem:** `ext4`
**rustc version:** `rustc 1.30.0-nightly (28bcffead 2018-09-01)`
**gcc version:** `gcc (GCC) 8.2.0` [`gcc (GCC) 8.2.1 20180831`]

## Machine 3 (Modern desktop)
I unfortunately do not have access to this machine at the moment, so I can't give exact version numbers, but I know that I updated pretty recently.

**OS:** `Arch Linux x86_64`
**Filesystem:** `ext4`

#### EDIT (2018-09-15):
**Kernel:** `4.18.1-arch1-1-ARCH`

**Comment by mre** [comment]
Thanks for the detailed info @ArniDagur.

Found this: 
> The call to splice() returns EINVAL when stdout refers to a non-seekable stream. I tried your program and it fails when stdout refers to the terminal. However, it succeeds when stdout is redirected to a regular file.

Might be related: https://stackoverflow.com/a/32221255/270334

**Comment by ArniDagur** [comment]
Replying to @mre's second comment:

On a freshly cloned repository:

**1. Does this happen in both release and debug builds?**

Yes.

**2. Can you maybe post an strace of your call to fcat?**

```
[arni: fcat (master)]$ RUST_BACKTRACE=1 target/release/fcat ~/.bashrc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EINVAL)', libcore/result.rs:983:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: fcat::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
**3. Can you try changing the buffersize and recompile?**

I tried the following and compiled in release mode:

1. `const BUF_SIZE: usize = 1024;`
2. `const BUF_SIZE: usize = 1024 * 16;` (the default)
3. `const BUF_SIZE: usize = 1024 * 64;`

The result is the same.

**Comment by ArniDagur** [comment]
Replying to @vbrandl's comment:
> Could you paste a gist containing the equivalent C code, you used?

The C program I referred to in `2` is not equivalent, but similar. I came across these blogposts when trying to debug a `tee` clone I wrote using `splice()` and `tee()` (which fails in the exact same way!), so they are more geared towards that.

2. http://papermint-designs.com/dmo-blog/2017-03-how-to-use-tee-and-splice
3. https://blog.superpat.com/2010/07/08/a-cup-of-tee-and-a-splice-of-cake/

**Comment by ArniDagur** [comment]
I tried on Ubuntu using the "Try Ubuntu without installing option" and interestingly enough, both `fcat` and my `tee` clone worked flawlessly.

**OS:** `Ubuntu 18.04.1 LTS x86_64`
**Kernel:** `4.15.0-29-generic`
**Filesystem:** [`iso9660`](https://en.wikipedia.org/wiki/ISO_9660)
![img_2008](https://user-images.githubusercontent.com/19227577/45592034-29877480-b952-11e8-91a5-7ae4d2a31a34.JPG)
**rustc version:** `rustc 1.29.0 (aa3ca1994 2018-09-11)`

**Comment by mre** [comment]
Few ideas:
* Quickly check if it also works with the latest `rustc`
* Can you mount your ext4 filesystem on Ubuntu and try again?
* Can you update the kernel somehow?

**Comment by ArniDagur** [comment]
I'll spare you the details of how I discovered this, but here's the gist of it:

1. `mv ~/.bashrc ~/.bashrc.bak`
2. `reboot`
3. log in

And `fcat` works without error. Then:

1. `mv ~/.bashrc.bak ~/.bashrc`
2. `reboot`
3. log in

And `fcat` stops working again.

---

**UPDATE**: Commenting out the following two lines fixes the issue:
```bash
eval $(keychain --agents gpg,ssh --quiet --eval id_rsa)
export GPG_TTY=$(tty)
```

Here's my `~/.bashrc`: (don't judge)

```bash
# vim: cc= :
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

# Terminal name style; generate one easily with: http://bashrcgenerator.com/
# Source git-prompt.sh to enable __git_ps1 command used in PS1 environment var.
source /usr/share/git/completion/git-prompt.sh
PS1='[\[$(tput sgr0)\]\[\033[38;5;9m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]: \[$(tput sgr0)\]\[\033[38;5;6m\]\W\[$(tput sgr0)\]\[\033[38;5;15m\]\[$(tput sgr0)\]\[\033[38;5;10m\]$(__git_ps1 " (%s)")\[$(tput sgr0)\]\[\033[38;5;15m\]]\\$ \[$(tput sgr0)\]'

# See: https://wiki.archlinux.org/index.php/SSH_keys#Keychain
eval $(keychain --agents gpg,ssh --quiet --eval id_rsa)
export GPG_TTY=$(tty)

# Source fzf files
[[ -f /usr/share/fzf/completion.bash ]] && source '/usr/share/fzf/completion.bash'
[[ -f /usr/share/fzf/key-bindings.bash ]] && source '/usr/share/fzf/key-bindings.bash'

# Add to path
[[ -d $HOME/miniconda3/bin ]] && export PATH="$HOME/miniconda3/bin:$PATH"
[[ -d $HOME/.gem/ruby/2.5.0/bin ]] && export PATH="$HOME/.gem/ruby/2.5.0/bin:$PATH"
[[ -d /opt/cuda/bin ]] && export PATH="/opt/cuda/bin:$PATH"
[[ -d $HOME/.cargo/bin ]] && export PATH="$HOME/.cargo/bin:$PATH"
# Set RUST_SRC_PATH, which is needed for Racer
if [ -x "$(command -v git)" ]; then
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi

# Config management alias; see the following for details:
# https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotflies-git-bare-repo/
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# Alias to fix pikaur on Anaconda/Miniconda systems:
alias pikaur='/usr/bin/python3 /usr/bin/pikaur'
```

@rahilwazir Do you mind sharing your ~/.bashrc with us?

**Comment by mre** [comment]
That's quite a tricky case. Kudos for following through!
I don't know how to go about this. Shall we mention that in the `README.md`?
If so, how? I'm thankful for any ideas or even pull requests.
My suspicion is, that it's because of the `eval` statement.  The `export GPG_TTY=$(tty)` should be fine, or?

**Comment by mre** [comment]
Closing this as it doesn't seem to be an issue with fcat. Thanks @ArniDagur for following through.

**Comment by SalimTerryLi** [comment]
Hi there?

Sorry for spamming this old thread, but I also have related issue. I'm using plain c to so `splice()` and it sometimes breaks with EINVAL for no reason, but I found a quick fix for that: just start `screen` and press enter to exit, then my program works without any issue. I'm linking it here: https://github.com/SalimTerryLi/linenoise

More confusing, if I use that workaround to successfully started my program, then the problem just won't happen again, even if I exit my bash and reopen it. It also seems breaks my stdin and made poll never return on POLLIN (the corresponding codes are not push to that repo yet)

It must be something that configures the tty into a strange state, but I have no idea what it is...
