### ISSUE TITLE
Fix issues with proptest crate

### ISSUE THREAD

**Issue by mre** [mre/fcat#23]
We have issues like that when bumping it to the latest version (see #22):
```203 | |     }
error[E0277]: the trait bound `rand_xorshift::XorShiftRng: rand_core::SeedableRng` is not satisfied
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/deprecated.rs:240:5
    |
240 |     type Seed = <::rand_xorshift::XorShiftRng as SeedableRng>::Seed;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_xorshift::XorShiftRng`

error[E0277]: the trait bound `rand_xorshift::XorShiftRng: rand_core::SeedableRng` is not satisfied
```

**Comment by vbrandl** [comment]
I just executed `cargo test` on the `dependabot/cargo/proptest-0.9.4` branch and everything worked fine.

```
$ cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)
$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
```

Proptest seems to have problems with Rust nightly (have a look at the CI logs: https://travis-ci.org/AltSysrq/proptest).

Did you use a nightly compiler?

**Comment by mre** [comment]
Yeah looks like once we fixed the issues with `assert_cmd`, the proptest branch passed CI. So after all we didn't have an issue with proptest I assume.
For reference, we're just testing on `stable` at the moment as per our [Github Actions settings](https://github.com/mre/fcat/blob/master/.github/workflows/rust.yml).

**Comment by mre** [comment]
Oh and thanks for checking and running the branch locally @vbrandl. 👍
