### ISSUE TITLE
`EMFILE` error when `cat`int too many files because pipes are not closed.

### ISSUE THREAD

**Issue by dzamlo** [mre/fcat#7]
For each file, there is a call to the `pipe` function to create a pipe. But the resulting pipe are never closed. This means than if you try to `cat` too man files, one of the call to pipe will fail with an `EMFILE` error (and the unwrap will panic).

The simple obvious solution is to just close the pipe each times.

But a more efficient solution would be to reuse the pipe. This would reduce the number of syscall per file by 3 (the `pipe` and the two `close`), which could have an impact if you try to `cat` a lot of small files.

**Comment by mre** [comment]
Oh wow! Nice catch. To be honest I never tried with more than two files, hehe. 😅 
Would you like to send a pull request to fix that?
I would prefer to reuse the pipes.
